/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-03-01 12:15:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class auth_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"bg-white w-full max-w-md rounded-2xl shadow-2xl overflow-hidden mx-auto mt-12\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex border-b border-gray-200\">\r\n");
      out.write("        <button id=\"loginTab\" onclick=\"switchTab('login')\"\r\n");
      out.write("                class=\"flex-1 py-4 text-center font-semibold text-indigo-600 border-b-2 border-indigo-600 focus:outline-none transition-colors cursor-pointer\">\r\n");
      out.write("            Sign In\r\n");
      out.write("        </button>\r\n");
      out.write("        <button id=\"signupTab\" onclick=\"switchTab('signup')\"\r\n");
      out.write("                class=\"flex-1 py-4 text-center font-semibold text-gray-500 border-b-2 border-transparent hover:text-indigo-500 focus:outline-none transition-colors cursor-pointer\">\r\n");
      out.write("            Sign Up\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"p-8\">\r\n");
      out.write("        <form id=\"loginForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth\" method=\"POST\" class=\"fade-in block\">\r\n");
      out.write("            <div class=\"text-center mb-8\">\r\n");
      out.write("                <h2 class=\"text-2xl font-bold text-gray-800\">Welcome Back</h2>\r\n");
      out.write("                <p class=\"text-gray-500 text-sm mt-1\">Please enter your details to sign in.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"login\"/>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"space-y-5\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"loginEmail\" class=\"block text-sm font-medium text-gray-700 mb-1\">Email Address</label>\r\n");
      out.write("                    <input type=\"email\" id=\"loginEmail\" name=\"email\" required\r\n");
      out.write("                           class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all\"\r\n");
      out.write("                           placeholder=\"you@example.com\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"flex justify-between items-center mb-1\">\r\n");
      out.write("                        <label for=\"loginPassword\" class=\"block text-sm font-medium text-gray-700\">Password</label>\r\n");
      out.write("                        <a href=\"#\" class=\"text-xs text-indigo-600 hover:text-indigo-800 font-medium\">Forgot\r\n");
      out.write("                            password?</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"password\" id=\"loginPassword\" name=\"password\" required\r\n");
      out.write("                           class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all\"\r\n");
      out.write("                           placeholder=\"*******\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\"\r\n");
      out.write("                        class=\"w-full bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2.5 rounded-lg shadow-md hover:shadow-lg transition-all active:scale-[0.98] cursor-pointer\">\r\n");
      out.write("                    Sign In\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"signupForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth\" method=\"POST\" class=\"fade-in hidden\">\r\n");
      out.write("            <div class=\"text-center mb-8\">\r\n");
      out.write("                <h2 class=\"text-2xl font-bold text-gray-800\">Create an Account</h2>\r\n");
      out.write("                <p class=\"text-gray-500 text-sm mt-1\">Join us today! It only takes a minute.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"login\"/>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"space-y-4\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"name\" class=\"block text-sm font-medium text-gray-700 mb-1\">Full Name</label>\r\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" required\r\n");
      out.write("                           class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all\"\r\n");
      out.write("                           placeholder=\"John Doe\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"signupEmail\" class=\"block text-sm font-medium text-gray-700 mb-1\">Email Address</label>\r\n");
      out.write("                    <input type=\"email\" id=\"signupEmail\" name=\"email\" required\r\n");
      out.write("                           class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all\"\r\n");
      out.write("                           placeholder=\"you@example.com\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"signupPassword\" class=\"block text-sm font-medium text-gray-700 mb-1\">Password</label>\r\n");
      out.write("                    <input type=\"password\" id=\"signupPassword\" name=\"password\" required\r\n");
      out.write("                           class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all\"\r\n");
      out.write("                           placeholder=\"Create a strong password\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\"\r\n");
      out.write("                        class=\"w-full bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2.5 rounded-lg shadow-md hover:shadow-lg transition-all mt-4 active:scale-[0.98] cursor-pointer\">\r\n");
      out.write("                    Create Account\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    String alertMessage = (String) request.getAttribute("alertMessage");
    if (alertMessage != null && !alertMessage.trim().isEmpty()) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Trigger the browser alert\r\n");
      out.write("    alert(\"");
      out.print( alertMessage );
      out.write("\");\r\n");
      out.write("</script>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    function switchTab(tab) {\r\n");
      out.write("        const loginForm = document.getElementById('loginForm');\r\n");
      out.write("        const signupForm = document.getElementById('signupForm');\r\n");
      out.write("        const loginTab = document.getElementById('loginTab');\r\n");
      out.write("        const signupTab = document.getElementById('signupTab');\r\n");
      out.write("\r\n");
      out.write("        const activeClasses = ['text-indigo-600', 'border-indigo-600'];\r\n");
      out.write("        const inactiveClasses = ['text-gray-500', 'border-transparent', 'hover:text-indigo-500'];\r\n");
      out.write("\r\n");
      out.write("        if (tab === 'login') {\r\n");
      out.write("            loginForm.classList.remove('hidden');\r\n");
      out.write("            signupForm.classList.add('hidden');\r\n");
      out.write("\r\n");
      out.write("            loginTab.classList.remove(...inactiveClasses);\r\n");
      out.write("            loginTab.classList.add(...activeClasses);\r\n");
      out.write("\r\n");
      out.write("            signupTab.classList.remove(...activeClasses);\r\n");
      out.write("            signupTab.classList.add(...inactiveClasses);\r\n");
      out.write("        } else {\r\n");
      out.write("\r\n");
      out.write("            signupForm.classList.remove('hidden');\r\n");
      out.write("            loginForm.classList.add('hidden');\r\n");
      out.write("\r\n");
      out.write("            signupTab.classList.remove(...inactiveClasses);\r\n");
      out.write("            signupTab.classList.add(...activeClasses);\r\n");
      out.write("\r\n");
      out.write("            loginTab.classList.remove(...activeClasses);\r\n");
      out.write("            loginTab.classList.add(...inactiveClasses);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
